/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    deals: Deal;
    'canonical-fares': CanonicalFare;
    'collection-runs': CollectionRun;
    'pending-raw-payloads': PendingRawPayload;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    deals: DealsSelect<false> | DealsSelect<true>;
    'canonical-fares': CanonicalFaresSelect<false> | CanonicalFaresSelect<true>;
    'collection-runs': CollectionRunsSelect<false> | CollectionRunsSelect<true>;
    'pending-raw-payloads': PendingRawPayloadsSelect<false> | PendingRawPayloadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  departureCity: string;
  destination: string;
  headlinePrice: number;
  referenceTotalPrice?: number | null;
  currency?: string | null;
  tripType?: ('one-way' | 'round-trip') | null;
  travelStartDate?: string | null;
  travelEndDate?: string | null;
  travelWindowLabel?: string | null;
  airline?: string | null;
  isDirect?: boolean | null;
  baggageInfo?: string | null;
  refundChangeSummary?: string | null;
  sourceLink?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  expiresAt: string;
  recommendationCopy?: string | null;
  valueTags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published' | 'expired') | null;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "canonical-fares".
 */
export interface CanonicalFare {
  id: number;
  sourceId: string;
  collectionRunId: string;
  airline: string;
  flightNumbers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  departureAirport: string;
  arrivalAirport: string;
  departureTime: string;
  arrivalTime: string;
  cabin: 'ECONOMY' | 'PREMIUM_ECONOMY' | 'BUSINESS' | 'FIRST';
  baggageFacts: string;
  priceAmount: number;
  currency: string;
  deepLink?: string | null;
  collectedAt: string;
  expiresAt: string;
  rawPayloadRef: string;
  returnDepartureAirport?: string | null;
  returnArrivalAirport?: string | null;
  returnDepartureTime?: string | null;
  returnArrivalTime?: string | null;
  stopCount?: number | null;
  stopAirports?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  refundChangePolicy?: string | null;
  bookingRestrictions?: string | null;
  taxAmount?: number | null;
  fareClass?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-runs".
 */
export interface CollectionRun {
  id: number;
  sourceId: string;
  status: 'running' | 'success' | 'partial' | 'failed';
  startedAt: string;
  completedAt?: string | null;
  searchParams:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  totalFaresCollected?: number | null;
  totalValidationPassed?: number | null;
  totalValidationFailed?: number | null;
  totalDuplicatesSkipped?: number | null;
  totalPersisted?: number | null;
  persistedFareIds?:
    | {
        fareId?: string | null;
        id?: string | null;
      }[]
    | null;
  errorMessages?:
    | {
        message?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pending-raw-payloads".
 */
export interface PendingRawPayload {
  id: number;
  sourceId: string;
  collectionRunId: string;
  providerFareId: string;
  rawPayload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  collectedAt: string;
  expiresAt: string;
  canonicalFareRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'canonical-fares';
        value: number | CanonicalFare;
      } | null)
    | ({
        relationTo: 'collection-runs';
        value: number | CollectionRun;
      } | null)
    | ({
        relationTo: 'pending-raw-payloads';
        value: number | PendingRawPayload;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  departureCity?: T;
  destination?: T;
  headlinePrice?: T;
  referenceTotalPrice?: T;
  currency?: T;
  tripType?: T;
  travelStartDate?: T;
  travelEndDate?: T;
  travelWindowLabel?: T;
  airline?: T;
  isDirect?: T;
  baggageInfo?: T;
  refundChangeSummary?: T;
  sourceLink?: T;
  publishedAt?: T;
  updatedAt?: T;
  expiresAt?: T;
  recommendationCopy?: T;
  valueTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "canonical-fares_select".
 */
export interface CanonicalFaresSelect<T extends boolean = true> {
  sourceId?: T;
  collectionRunId?: T;
  airline?: T;
  flightNumbers?: T;
  departureAirport?: T;
  arrivalAirport?: T;
  departureTime?: T;
  arrivalTime?: T;
  cabin?: T;
  baggageFacts?: T;
  priceAmount?: T;
  currency?: T;
  deepLink?: T;
  collectedAt?: T;
  expiresAt?: T;
  rawPayloadRef?: T;
  returnDepartureAirport?: T;
  returnArrivalAirport?: T;
  returnDepartureTime?: T;
  returnArrivalTime?: T;
  stopCount?: T;
  stopAirports?: T;
  refundChangePolicy?: T;
  bookingRestrictions?: T;
  taxAmount?: T;
  fareClass?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-runs_select".
 */
export interface CollectionRunsSelect<T extends boolean = true> {
  sourceId?: T;
  status?: T;
  startedAt?: T;
  completedAt?: T;
  searchParams?: T;
  totalFaresCollected?: T;
  totalValidationPassed?: T;
  totalValidationFailed?: T;
  totalDuplicatesSkipped?: T;
  totalPersisted?: T;
  persistedFareIds?:
    | T
    | {
        fareId?: T;
        id?: T;
      };
  errorMessages?:
    | T
    | {
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pending-raw-payloads_select".
 */
export interface PendingRawPayloadsSelect<T extends boolean = true> {
  sourceId?: T;
  collectionRunId?: T;
  providerFareId?: T;
  rawPayload?: T;
  collectedAt?: T;
  expiresAt?: T;
  canonicalFareRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}