import type { DealFeedRecord } from './feed-query'

export const mockDeals: DealFeedRecord[] = [
  {
    id: 'deal-seoul-weekend',
    title: '上海-首尔周末往返直飞',
    departureCity: '上海',
    destination: '首尔',
    region: '周边国际',
    travelWindowLabel: '周末捡漏',
    airline: '东方航空',
    headlinePrice: 1399,
    referenceTotalPrice: 1680,
    valueScore: 88,
    status: 'published',
    publishedAt: '2026-04-10T08:00:00.000Z',
    updatedAt: '2026-04-11T06:00:00.000Z',
    expiresAt: '2026-04-30T23:59:59.000Z',
    baggageInfo: '20kg 托运 + 7kg 随身',
    refundChangeSummary: '改签手续费 280 元起，退票按舱位规则扣费',
    stopSummary: '直飞',
    cabin: '经济舱',
    restrictions: '不含五一当日出发班期',
    sourceName: '航司官网',
    sourceLink: 'https://example.com/deals/seoul-weekend',
    recommendationCopy: '红眼去白天回，适合周末短逃离',
    valueReasons: ['直飞周末出行', '税费后总成本仍低于均值', '回程时段友好']
  },
  {
    id: 'deal-bangkok-holiday',
    title: '广州-曼谷节假日前后含托运',
    departureCity: '广州',
    destination: '曼谷',
    region: '海岛/东南亚',
    travelWindowLabel: '节假日前后',
    airline: '泰国亚洲航空',
    headlinePrice: 1499,
    referenceTotalPrice: 1820,
    valueScore: 84,
    status: 'published',
    publishedAt: '2026-04-09T10:30:00.000Z',
    updatedAt: '2026-04-11T02:00:00.000Z',
    expiresAt: '2026-05-05T23:59:59.000Z',
    baggageInfo: '15kg 托运 + 7kg 随身',
    refundChangeSummary: '不可退，可付费改期',
    stopSummary: '直飞',
    cabin: '经济舱',
    restrictions: '节假日当天出发价差较大',
    sourceName: 'OTA 平台',
    sourceLink: 'https://example.com/deals/bangkok-holiday',
    recommendationCopy: '适合 4-5 天假期，价格波动可控',
    valueReasons: ['含托运行李', '避开高峰日后更划算', '航班时段稳定']
  },
  {
    id: 'deal-hk-hop',
    title: '深圳-香港快线中转联运',
    departureCity: '深圳',
    destination: '香港',
    region: '周末捡漏',
    travelWindowLabel: '周末捡漏',
    airline: '香港航空',
    headlinePrice: 699,
    referenceTotalPrice: 860,
    valueScore: 79,
    status: 'published',
    publishedAt: '2026-04-11T07:00:00.000Z',
    updatedAt: '2026-04-11T08:00:00.000Z',
    expiresAt: '2026-04-20T23:59:59.000Z',
    baggageInfo: '仅随身 7kg，托运需加购',
    refundChangeSummary: '退改手续费较高，建议确定行程再下单',
    stopSummary: '巴士接驳 + 航段',
    cabin: '经济舱',
    restrictions: '联运衔接时间需自行确认',
    sourceName: 'OTA 平台',
    sourceLink: 'https://example.com/deals/hk-hop',
    recommendationCopy: '预算友好，适合短途补货型出行',
    valueReasons: ['入门价低', '更新时间新', '周末班次多']
  },
  {
    id: 'deal-osaka-sakura',
    title: '北京-大阪樱花季早鸟',
    departureCity: '北京',
    destination: '大阪',
    region: '周边国际',
    travelWindowLabel: '樱花季',
    airline: '海南航空',
    headlinePrice: 1899,
    referenceTotalPrice: 2250,
    valueScore: 92,
    status: 'published',
    publishedAt: '2026-04-08T09:00:00.000Z',
    updatedAt: '2026-04-10T09:00:00.000Z',
    expiresAt: '2026-05-20T23:59:59.000Z',
    baggageInfo: '23kg 托运 + 7kg 随身',
    refundChangeSummary: '退票扣 15%，改签按差价 + 手续费',
    stopSummary: '直飞',
    cabin: '经济舱',
    restrictions: '热门日期需尽快锁价',
    sourceName: '航司官网',
    sourceLink: 'https://example.com/deals/osaka-sakura',
    recommendationCopy: '价值分高，适合提前确定行程的人群',
    valueReasons: ['旺季仍在合理区间', '含标准托运', '退改规则可预期']
  },
  {
    id: 'deal-expired-sample',
    title: '杭州-三亚已过期示例',
    departureCity: '杭州',
    destination: '三亚',
    region: '海岛/东南亚',
    travelWindowLabel: '海岛',
    airline: '南方航空',
    headlinePrice: 999,
    referenceTotalPrice: 1300,
    valueScore: 70,
    status: 'published',
    publishedAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-03-02T00:00:00.000Z',
    expiresAt: '2026-03-03T00:00:00.000Z',
    baggageInfo: '15kg 托运',
    refundChangeSummary: '示例数据',
    stopSummary: '直飞',
    cabin: '经济舱',
    restrictions: '示例数据',
    sourceName: '示例来源',
    sourceLink: 'https://example.com/deals/expired',
    recommendationCopy: '示例数据',
    valueReasons: ['示例']
  }
]
